services:

  php:
    build: ./php
    environment:
      - SMTP_PORT=1025
      - SMTP_HOST=mail
      - SMTP_AUTH=false
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html/public
    entrypoint: ["php", "-S", "0.0.0.0:80"]
    depends_on:
      - mail

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
